name: Test and build
on:
  push:
    branches:
      - "**"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Lint cli app
        run: npm run lint-cli

      - name: Build smart contract
        run: npm run build-contract
      - name: Test cli app
        run: npm run test-cli

      - name: Build cli app
        run: npm run build-cli
