name: Test and build
on:
  push:
    branches:
      - "**"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm ci
      - name: Install truffle
        run: npm install -g truffle

      - name: Lint cli app
        run: npm run lint

      - name: Build smart contract
        run: cd smart_contract && truffle build && cd ..
      - name: Test cli app
        run: npm run test

      - name: Build cli app
        run: npm run build
