name: Test and build
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    - uses: actions/checkout@v3
    - name: Lint
      run: npm run lint
  test:
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: npm run test
  build:
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm run build